### PR TITLE
(Bug) Keep data between the steps (Integration Branch)

### LINKED ISSUE #1033: (Bug) Keep data between the steps
As a user, I want the application to keep the data until the end and allow me to go back, keeping the data between the steps.

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Ropsten

### If you were able to create it, what is the URL of your crowdsale?

None

### Do you have screenshots showing the problem?

None

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

None

---

### PR DESCRIPTION
**Pull request by mariano-aguero**
This is a PR with an integration branch
Closes #1033 

Pull request covering the steps

- [x] Step 1 #1070 
- [x] Step 2 #1071
- [x] Step 3 #1081
- [x] Step 4 #1097 
- [x] Manage section #1103 

Once the steps are merged, an integral test would have to be carried out

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Issue in Step3: field Supply disabled if whitelist enabled, both for Minted and Dutch.
Expected: field Supply should be disabled  if at least 1 whitelisted address has added 
screen shot 2018-08-28 at 9 00 12 am

**Comment by mariano-aguero** [comment]
Hi @dennis00010011b 

> Issue in Step3: field Supply disabled if whitelist enabled, both for Minted and Dutch.

I change how validate the supply input, Regards

**Comment by dennis00010011b** [comment]
Hi @mariano-aguero 
>I change how validate the supply input, Regards

It fixed

**Comment by fernandomg** [comment]
Before merging/approving this PR, this must be solved: https://github.com/poanetwork/token-wizard/pull/1103#issuecomment-415080605

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Before merging/approving this PR, this must be solved: #1103 (comment)

Can you check de fix for the above comment? Thanks

**Comment by dennis00010011b** [comment]
@mariano-aguero 
it fixed https://github.com/poanetwork/token-wizard/pull/1103#issuecomment-415080605

**Comment by dennis00010011b** [comment]
@mariano-aguero
Contribution page:  app crashed if network changed
Steps: 
1. Set network Sokol
2. Create Minted crowdsale with any valid parameters
3. Open contribution page as an owner
4. Set network Rinkeby(or any other)
5. Confirm warning, observe page.

Expected result:  
 -warning should be displayed 'switch to Sokol network .........'
Actual result : 
 - app crashed, error message

screen shot 2018-09-03 at 3 50 28 am

[contrib_grash.log](https://github.com/poanetwork/token-wizard/files/2345239/contrib_grash.log)

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Contribution page: app crashed if network switched

I change how network is validated, separate it from the rest of the environment check

**Pull request merged**
