### PR TITLE
(Feature) Apply new design to step 6: "Contribute"

### LINKED ISSUE #1090: Apply new design to Step 6 - Contribute
Child of #1082

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #1090

**Description:**

New styles for the Contribute section.

Changed the circle component for one more adequate to the desired results.

And @mariano-aguero fixed the erratic behavior of the backwards ticking circle / clock.

**Screenshots:**

localhost_3000_1 laptop with mdpi screen
localhost_3000_1 ipad
localhost_3000_contribute_addr 0x856be5c59dcf928cbe0cbcc70534090b21420646 networkid 3 ipad
localhost_3000_contribute_addr 0x856be5c59dcf928cbe0cbcc70534090b21420646 networkid 3 nexus 6p

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@gabitoesmiapodo
1. Should be 'proxy address' instead 'Execution ID'
2. Should be icon copy for current account

screen shot 2018-11-23 at 12 47 37 pm

**Comment by dennis00010011b** [comment]
@gabitoesmiapodo 
Ticker always should be in capital letters even if user has entered it in lower case on Step 2

screen shot 2018-11-23 at 1 27 10 pm

**Comment by dennis00010011b** [comment]
@gabitoesmiapodo 
Contribute with QR code
1. Change text `Send ethers to the Auth-os Proxy smart-contract address with a MethodID: `
                    to `Send ethers to the crowdsale proxy address with a data: `

2. Add copy icon for data

screen shot 2018-11-23 at 2 00 39 pm

**Comment by dennis00010011b** [comment]
@gabitoesmiapodo 
1. Word 'Crowdsales' starts from capital letter, should be lower case 
2. Contribution's dimension should be `Tokens` , not `Token` 
screen shot 2018-11-23 at 2 11 50 pm

**Comment by dennis00010011b** [comment]
@gabitoesmiapodo 
Text size of text  'Contribute page ' less than  others

screen shot 2018-11-23 at 2 28 36 pm

**Comment by dennis00010011b** [comment]
@gabitoesmiapodo 
Total amount of tiers is incorrect
Steps:
 1. Create minted crowdsale with 2 tiers
 2. Wait until 1 tiers is finished
 3. Contribute any amount in tier 2
 
screen shot 2018-11-23 at 2 35 31 pm

**Comment by dennis00010011b** [comment]
@gabitoesmiapodo 
Error message overlapped
screen shot 2018-11-23 at 2 45 52 pm

**Comment by dennis00010011b** [comment]
@gabitoesmiapodo 
In the dutch case  the balance  goes beyond of block's border
Would be better to round to 3rd decimal? For all token'
screen shot 2018-11-26 at 09 12 06
s values on the page

**Comment by gabitoesmiapodo** [comment]
@dennis00010011b

- > Should be 'proxy address' instead 'Execution ID' -> Changed it.
- > Should be icon copy for current account -> Added.
- > Ticker always should be in capital letters even if user has entered it in lower case on Step 2 -> Fixed.
- > Change text Send ethers to the Auth-os Proxy smart-contract address with a MethodID: 
to Send ethers to the crowdsale proxy address with a data: -> Changed it.
- > Add copy icon for data -> Added it.
- > There isn't warning Think twice before contributing to Crowdsales. Tokens will be deposited on a wallet you used to buy tokens. It only for 'Wallet ' option now, not for QR -> Fixed, it's always on now.
- > Word 'Crowdsales' starts from capital letter, should be lower case -> Fixed it.
- > Contribution's dimension should be Tokens , not Token -> Fixed it.
- > Text size of text 'Contribute page ' less than others -> That's in the design: https://zpl.io/bJqgnXx Not sure if it's a mistake or not, or why it's like that.
- > Total amount of tiers is incorrect -> @mariano-aguero will address that.
- > Error message overlapped -> Fixed.
- > In the dutch case the balance goes beyond of block's border. Would be better to round to 3rd decimal? For all token' -> Not sure about rounding the numbers, but token values should wrap now.

**Comment by dennis00010011b** [comment]
@gabitoesmiapodo 
Button 'Contribute' doesn't look like disabled when it is really disabled (isn't allowed to buy)
Needs make it in gray color  or use special mouse cursor 
screen shot 2018-11-26 at 13 36 06

**Comment by dennis00010011b** [comment]
@gabitoesmiapodo @mariano-aguero 
Minted, 2 tiers: investor can't buy in second tier if already has bough total supply in 1st tier
Steps:
 1. Create Minted crowdsale,2 tiers,  no whitelist, mincaps = 0
 2. Buy full supply for tier 1 
 3. Wait until 2nd tier starts
 4. Try to buy from the same account 

Expected result: 
 - investor should be allowed to buy in 2nd tier

Actual result: 
 - investor can't buy
 - fields 'min/max contribution' have value = 'you are not allowed'

This issue isn't reproducible in branch 2.0

screen shot 2018-11-26 at 14 33 08

**Comment by gabitoesmiapodo** [comment]
@dennis00010011b 

> Button 'Contribute' doesn't look like disabled when it is really disabled (isn't allowed to buy)
Needs make it in gray color or use special mouse cursor -> Button's style is the same that's being used all around the DApp (it's shared). It looks good to me, and I think it should be consistent with everything else in the design.

I added the "not-allowed" cursor as suggested, anyway.

**Comment by dennis00010011b** [comment]
@gabitoesmiapodo @mariano-aguero 
Everything looks good except https://github.com/poanetwork/token-wizard/pull/1230#issuecomment-441829978

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Everything looks good except #1230 (comment)

I'm working on this, I see an issue created for this #1235
The rest LGTM

Regards

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Minted, 2 tiers: investor can't buy in second tier if already has bough total supply in 1st tier
> Steps:
> 

> Create Minted crowdsale,2 tiers, no whitelist, mincaps = 0
> Buy full supply for tier 1
> Wait until 2nd tier starts
> Try to buy from the same account
> Expected result:

> investor should be allowed to buy in 2nd tier
> Actual result:

> investor can't buy
> fields 'min/max contribution' have value = 'you are not allowed'
> This issue isn't reproducible in branch 2.0

There is a bug in the method getCurrentTierInfo of the contracts.They can not be modified because they have already been audited.
I fixed with a 'retry' approach, so you  will see a "Waiting ..." label until the data is as expected.
The button 'Contribute'' will be enabled when the data is completely propagated in the blockchain.

**Comment by dennis00010011b** [comment]
@mariano-aguero @gabitoesmiapodo 
 After tier has been sold the timer's count is still displayed after switching account in NW 
https://www.useloom.com/share/a9333be153d04a37aee18994372b2687

**Comment by dennis00010011b** [comment]
Time format should be `hh:mm` ,ex. `00:09`, not` 0:9`
screen shot 2018-11-27 at 23 50 30

**Comment by mariano-aguero** [comment]
@dennis00010011b 
> Time format should be `hh:mm` ,ex. `00:09`, not` 0:9`

Fixed

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> @mariano-aguero @gabitoesmiapodo
> After tier has been sold the timer's count is still displayed if switches account in NW
> 
> https://www.useloom.com/share/a9333be153d04a37aee18994372b2687

Fixed

**Comment by mariano-aguero** [comment]
@dennis00010011b 

Remember to close this issue #1235 if is all OK

Regards

**Comment by dennis00010011b** [comment]
> @dennis00010011b
> 
> > @mariano-aguero @gabitoesmiapodo
> > After tier has been sold the timer's count is still displayed if switches account in NW

> 
> Fixed

Clock isn't displayed now but there is should be text: "crowdsale has ended" 

screen shot 2018-11-28 at 10 49 22

**Comment by dennis00010011b** [comment]
@mariano-aguero @gabitoesmiapodo 
Incorrect error message if enter incorrect value before start of crowdsale . Should be `You are not allowed`

screen shot 2018-11-28 at 17 31 09

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Clock isn't displayed now but there is should be text: "crowdsale has ended"

> Incorrect error message if enter incorrect value before start of crowdsale . Should be You are not allowed

Done

**Comment by gabitoesmiapodo** [comment]
@dennis00010011b 

Since development of TW is halting for now (see https://medium.com/poa-network/farewell-token-wizard-2-0-time-to-reprioritize-8cbd7319a97b), I think we need to keep this issue / PR exclusively for the rebranding / visual style related work.

Please create separate issues for any new business logic related problems you may find, as these problems still exist and we or anyone else might fix them in the future.

If there aren't any more visual problems and we have your approval for this PR we will proceed to merge it and finish this part of the job.

**Comment by dennis00010011b** [comment]
@mariano-aguero 
> 
> > Incorrect error message if enter incorrect value before start of crowdsale . Should be `You are not allowed`
> 
> Done

There is error message If correct value is entered before start. Shouldn't be any error message in such case,  button 'Contribute' should be enabled, should be  popup '"Wait, please. Crowdsale company hasn't started yet. It'll start from....'

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> @mariano-aguero
> 
> > > Incorrect error message if enter incorrect value before start of crowdsale . Should be `You are not allowed`
> > 
> > 
> > Done
> 
> There is error message If correct value is entered before start. Shouldn't be any error message in such case, button 'Contribute' should be enabled, should be popup '"Wait, please. Crowdsale company hasn't started yet. It'll start from....'

Updated the behaviour

**Pull request merged**
