### PR TITLE
(Feature) Validate imported whitelist addresses

### LINKED ISSUE #641: (Improvement) Validate imported whitelist addresses
See #639.

### PR DESCRIPTION
**Pull request by fvictorio**
Depends on #656. Closes #641.

### CODE REVIEW

**Comment by vbaranov** [comment]
@fvictorio could you clarify which types of validations we cover with this PR? do we need more validations, or it covers all possible validations?

**Comment by fvictorio** [comment]
It performs the same validation that are done when you type an address in the input (it just uses `Web3.util.isAddress`).

**Comment by vbaranov** [comment]
Ok, I see. The issue is that when we import an address with individual min cap > individual max cap there is no validation for now. will it be resolved in the frame of https://github.com/poanetwork/token-wizard/issues/578 ?

**Comment by fvictorio** [comment]
Oh, no, the min an max cap are not being validated (it just checks that they are numbers). We should think of a way to have those validations in a single place and use that both when importing a CSV and when typing an address.

Do you think we should do that as part of this PR?

**Comment by vbaranov** [comment]
>Do you think we should do that as part of this PR?

No. I think we could merge it. I mentioned here just to not forget to do this as a part of #578 or as a separate issue. @fvictorio please create a new issue if you prefer to do it on a separate one.

**Pull request merged**
