### PR TITLE
(Fix) Dutch auction crowdsale support for new Registry

### PR DESCRIPTION
**Pull request by vbaranov**
Dutch auction crowdsale support for updated Auth-os Registry [v.1.0.4](https://github.com/auth-os/core/releases/tag/1.0.4)

### CODE REVIEW

**Comment by dennis00010011b** [comment]
Manage page: whitelisted maxCap increasing (without purchase), should be constant
Tier duration is 15 min, minRate=100, maxRate = 1000
screen shot 2018-06-16 at 16 30 25
screen shot 2018-06-16 at 16 30 43

**Comment by dennis00010011b** [comment]
Crowdsale with minCap, Contribution page: no validation for minCap value

screen shot 2018-06-16 at 17 01 58

**Comment by vbaranov** [comment]
@dennis00010011b 
>Manage page: minCap for whitelisted addresses always zero
>Crowdsale with minCap, Contribution page: no validation for minCap value

thanks, both are fixed.

>Manage page: whitelisted maxCap increasing (without purchase), should be constant
Tier duration is 15 min, minRate=100, maxRate = 1000

I'll address it to Auth-os, if they can fix it.

**Comment by dennis00010011b** [comment]
@vbaranov 
Contribution page: status 'crowdsale has ended' displayed if  accountis switched  to whitelisted address. But address still can buy and page return  to normal behavior after purchase.
Steps to reproduce:
1. Create Dutch crowdsale with whitelist
2. Switch metamask to any whitelisted account 
3. Open contribution page , refresh it.
screen shot 2018-06-18 at 08 26 18

**Comment by fernandomg** [comment]
> @vbaranov
Contribution page: status 'crowdsale has ended' displayed if accountis switched to whitelisted address. But address still can buy and page return to normal behavior after purchase.
Steps to reproduce:

I was about to report the same issue.

The problem is in this line: https://github.com/poanetwork/token-wizard/blob/fac8a5e0d740507c6b4e0fdef94f659270266ddf/src/components/crowdsale/utils.js#L372

It should return `minimumPurchaseAmt` instead of `minimum_purchase_amt`

**Comment by vbaranov** [comment]
@dennis00010011b @fernandomg tnx, fixed.

**Pull request merged**
