### PR TITLE
(Fix) Home [New Crowdsale] button is not cleaning the localStorage

### LINKED ISSUE #1182: (Fix) Home [New Crowdsale] button is not cleaning the localStorage
**Problem:** In the integration branch (which is already merged with `2.0`) the cleaning of the `localStorage` when the user clicks on [New Crowdsale] button is no longer working.

**Solution:** Create a PR from the integration branch (`integration/#1082-new-design`) and copy the behavior from `2.0`.

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #1182

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Minted: Step 2 page  doesn't keep state if move back/forward
https://www.useloom.com/share/3667c17b686441eab8300ede3987c653
Steps:
 1. Start new crowdsale
2. Select Minted, continue
3. Fill out fields name and ticker on Step 2
4. Go back using browser's button
5.Go forward using browser's button
Expected result: fields name and ticker on Step 2 should keep previously entered data

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Minted: Step 2 page doesn't keep state if move back/forward

Solved, checked tests

screenshot_20181018_152057

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Same things with Step 1:  page doesn't keep state if move back/forward
https://www.useloom.com/share/2f482e5152c1453aaedc55177159d003

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Same things with Step 1: page doesn't keep state if move back/forward

Done

**Pull request merged**
