### PR TITLE
(Feature) New design for home / landing page

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
**Description:**

Implemented the new designs for the Token Wizard's home page, and also some common elements like modal windows, and a full screen loading component.

Notes:

- Add ?uiversion=2 as a parameter (ie: http://localhost:3000/?uiversion=2) to test using only the new styles. Otherwise the old styles will be used.
- I used some temporary data to fill the crowdsale's data table, so your results will be obviously different.

**Designs (Zeplin):**

- Desktop: https://zpl.io/V419yrJ
- Mobile: https://zpl.io/aN0nvgQ

**Some screenshots:**

Desktop:

1- desktop
2- desktop
3- desktop
4- desktop

Tablet:

1- tablet
2- tablet
3- tablet
4- tablet

Mobile:

1-mobile
2- mobile
3- mobile
4- mobile

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@gabitoesmiapodo
Chrome  Version 68.0.3440.106 (Official Build) (64-bit)
Choose crowdsale list: selected item isn't highlighted

screen shot 2018-09-03 at 1 32 53 pm

**Comment by dennis00010011b** [comment]
@gabitoesmiapodo
Desktop, MacOS, Chrome Version 68.0.3440.106 (Official Build) (64-bit)
Home page:
 - there are no icons for: Twitter, POA, Telegram, GitHub, Gitter https://github.com/poanetwork/token-wizard/issues/1102
 All of these are presented in old version
screen shot 2018-09-03 at 1 34 44 pm

**Comment by dennis00010011b** [comment]
@gabitoesmiapodo
Desktop, MacOS, Chrome Version 68.0.3440.106 (Official Build) (64-bit)
Home page: `Auth_os` text doesn't look like link

screen shot 2018-09-03 at 1 45 40 pm

**Comment by fernandomg** [comment]
Adding to https://github.com/poanetwork/token-wizard/pull/1122#issuecomment-418189319

The mouse cursor doesn't indicate that the row is clickable.

An example from v1.0
image

**Comment by fernandomg** [comment]
> And it seems, that style of the list of addresses popup differs from that one from the layout app.zeplin.io/project/5b38672635f4e0a932ec246f/screen/5b3895a9c615fa114ec71dde. Will it be subject of another PR?

@vbaranov I'm not understanding that new screen. Looks like an enhanced ManageScreen?

What confuses me is this mock https://app.zeplin.io/project/5b38672635f4e0a932ec246f/screen/5b3895a97279af2b6e2ddf3d that treats each item as a list of ordered steps (taking into account to how they are highlighted in the bullet-list)

**Comment by gabitoesmiapodo** [comment]
@fernandomg

- In Firefox it looks a bit weird -> It should be fixed now.
- Mobile-view in Firefox Desktop (it doesn't scrolls) -> Fixed too.
- The mouse cursor doesn't indicate that the row is clickable. -> Fixed.

@dennis00010011b

- Choose crowdsale list: selected item isn't highlighted -> Fixed.
- There are no icons for: Twitter, POA, Telegram, GitHub, Gitter #1102. All of these are presented in old version / Home page: Auth_os text doesn't look like link -> We should ask @pashagonchar about that, because current designs are like what I've implemented.

@vbaranov

- Let's change logo asset to a transparent background -> Changed it for the SVG version (for some reason I chose the PNG version before).
- And it seems, that style of the list of addresses popup differs from that one from the layout https://app.zeplin.io/project/5b38672635f4e0a932ec246f/screen/5b3895a9c615fa114ec71dde. Will it be subject of another PR? -> I think that's a bigger change than simply a restyling (more like a new feature). It will require some workflow and programming changes that I think should be implemented in a new issue. 

For now this popup it's just restyled like the modal windows in the new designs.

**Comment by fernandomg** [comment]
@gabitoesmiapodo everything fixed.

Now the main-info box is not properly aligned vertically (in both, firefox and chrome).
image

It depends on the resolution though because there are cases where it's properly aligned.
image

**Comment by vbaranov** [comment]
>What confuses me is this mock https://app.zeplin.io/project/5b38672635f4e0a932ec246f/screen/5b3895a97279af2b6e2ddf3d that treats each item as a list of ordered steps (taking into account to how they are highlighted in the bullet-list)

@fernandomg @gabitoesmiapodo Sorry for confusion. I am not about the list of steps in the left menu or changing the logic. I am just talking about the representation of the modal window. 

From this PR it looks like



But from the layout it should be like:



But I am sure, that it could be made in a separate PR and it shouldn't stop to merge this one.

**Comment by gabitoesmiapodo** [comment]
@fernandomg I think it might be that you are forgetting to add the ?uiversion=2 parameter? That's what happens to me, at least.

Added a few CSS improvements anyway, just in case.

If that's not the case I will need some more info, as screen resolution, etc.

@vbaranov 

I just adapted the general modal windows and tables styles to look like this https://zpl.io/2ymGX4n and that's why it looks that way now. But that will not be the final implementation.

That said, it will be necessary more than a simple modal restyling to make this:

https://zpl.io/brNpKB7 
https://zpl.io/2vYjBkv
https://zpl.io/2EA4wpn

because it changes completely what we have now, and that's why I think it would be better to implement that feature in a new issue.

**Comment by vbaranov** [comment]
@gabitoesmiapodo ok, let's leave it as is for now. Representation of this modal window needs to be discussed with a designer...

**Comment by fernandomg** [comment]
I've added tests for the `Home` Component.

Updated tests for `Load` and  `CrowdsaleList` components as well.

Also modified `Home` component and created a `navigateTo` method to facilitate testing.

All test cases related to `CrowdsaleList` weren't added as it will be moved to a new component instead of being displayed as a modal window.  

---

There's a test case that failed and due to time constraints, I decided to create a separate issue (#1129) to solve it as it's taking too much time.

**Pull request merged**
