### PR TITLE
(Bug) Publish page: start/end time have no timezone

### LINKED ISSUE #1126: (Bug) Publish page: start/end time have no timezone
Steps:
 1. Create any valid crowdsale
 2. Open publish page and observe fields start/end time.

Expected result: timezone should be displayed
Actual result:  no timezone specified

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Sokol*

### If you were able to create it, what is the URL of your crowdsale?

*http://localhost:3000/crowdsale?addr=0xdd57b2841b4a77d11c370212fbda81d2c4243e21&networkID=77*

### Do you have screenshots showing the problem?
screen shot 2018-09-04 at 1 07 30 pm

### Do you see errors in the dev console? If yes, please include a screenshot
*No*

---

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #1126 and #1127

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Publish page - time displayed in format: Greenwich time (UTC+0) + local time zone

screen shot 2018-09-12 at 12 23 53 pm


Let start time is 2018-09-12 11:20 (UTC -0)
We have  two option how to render time in publish page:
 1. Calculate local machine time , it will be  `2018-09-12 04:20 (UTC -7)`  for user from Seattle.
 2. Just render UTC+0 time: `2018-09-12 11:20 (UTC -0)`

I think 2nd option is enough. The same should be in files

**Comment by fernandomg** [comment]
@mariano-aguero 

The start time for the crowdsale is `14:25GMT-3`, and indeed it started at that time. But in the summary file downloaded I'm getting a start time of `17:25GMT-3`.

Here's a snapshot with that info:
image

**Comment by fernandomg** [comment]
@mariano-aguero continuing with the previous message... despite the crowdsale has started in the UI, I'm not allowed to contribute because the start time was set to `17:25GMT-3` instead.

image

And you can check that that's the time stored in the contract:
image

Crowdsale Address: `0x164a545bd972c022ae633760e213aa9ec649f858`

**Comment by dennis00010011b** [comment]
@mariano-aguero 
manage page: start/end time is displayed as UTC+0000, should be local machine time

screen shot 2018-09-25 at 11 08 46 am

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Manage page: button `Save` always enabled
Steps:
 1. Create Minted or Dutch crowdsale with valid parameters
 2. Open manage page and observe button `Save`
screen shot 2018-09-26 at 3 48 05 pm

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Is it ready for review?

**Comment by mariano-aguero** [comment]
@dennis00010011b 

I need to solve the problem in the contribution page

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Manage page: button Save always enabled
Contribution not allowed

Done, now is ready

Regards

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Tested with Minted crowdsale, modifiable, 1 tier, no whitelist
Sokol, proxyID 0xaa4a8cf344ec89e5708c7b642ad23ea4e13445ef
Manage page: 
 1. Button 'Save ' always enabled
    Should be enabled only if any changing was made
2. End time isn't modifiable
     End time should be modifiable  before tier's start if tier is modifiable
3. Can not change mincap after start of tier
4. Changing mincap before start of crowdsale triggered 2 transaction

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Dutch/ Minted- Contribution page: no warning if user tries to contribute before start, transaction is gereated
screen shot 2018-10-01 at 8 58 00 am

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Dutch/ Minted- Contribution page: no warning if user tries to contribute before start, transaction is generated

Done

**Pull request merged**
