### PR TITLE
(Fix) loader not loading after deployment has finished

### LINKED ISSUE #566: (Fix) all steps are finished, but loader is not hidden
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Mainnet

### If you were able to create it, what is the URL of your crowdsale?

No

### Do you have screenshots showing the problem?

photo5172861386307512277

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

No

---

### PR DESCRIPTION
**Pull request by fernandomg**
Closes #566 

Seems that the user closed the deployment steps modal, and the process was lacking of the option to close the _loading_ overlay.

### CODE REVIEW

**Comment by fvictorio** [comment]
Should we also change the `userHideModal` function? The second line:

```
    if (!this.props.deploymentStore.deploymentHasFinished) this.setState({ loading: true })
```

seems redundant now, doesn't it?

**Comment by fernandomg** [comment]
@fvictorio you mean to change it to:
```
this.setState({ loading: !this.props.deploymentStore.deploymentHasFinished })
```
?

**Comment by fvictorio** [comment]
I'd just remove it, and handle the loader independently of the modal.

**Comment by fernandomg** [comment]
I did removed the `Loader

**Pull request merged**
