### PR TITLE
(Bug) There is no Proxy contract address in zip archive (Minted capped only) 

### LINKED ISSUE #1150: (Bug) There is no Proxy contract address in zip archive (Minted capped only)
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Sokol

### If you were able to create it, what is the URL of your crowdsale?

/contribute?addr=0x50642d64fbf63e59a1500661c96a4daedf3f3f16&networkID=77

### Do you have screenshots showing the problem?

I have created 2 tiered Minted caped crowdsale.
**Auth-os_addresses.txt** doesn't contain the address of Proxy smart contract. The problem is only with Minted capped crowdsale. There is no such problem with Dutch Auction crowdsale.

The content of the file:
```
*****************************
*******AUTH-OS METADATA******
*****************************

**********REGISTRY***********

Auth-os abstract storage address: 0x9d126f44151f70a4da03f53fcb485dea6c0b8d64
Auth-os registry idx address: 0x76fafe6f7e2f25e40664cf9f22d6e18b709d0087
Auth-os script executor address: 0x6865f64ecb1f0222a0febe5c1fc1b40c7a378da6
Auth-os provider address: 0x663d2feb6af69867e0144aab82624edb7af1728b
*********CROWDSALE***********

Auth-os application name: MintedCappedCrowdsale
Auth-os execution ID: 0x000000000000000000000000eeaefd3a69f7d10db92205bbaa54f7c5aa8edf3f
Auth-os MintedCappedIdx address: 0xeeaefd3a69f7d10db92205bbaa54f7c5aa8edf3f
Auth-os Sale address: 0x1d9702eb87c47f90c8669f3d36322f8cf985f721
Auth-os Token address: 0xbe1efbd9134bb5cd0ad3ee6cd2c246e56961ac5c
Auth-os Sale manager address: 0x3ab54a53eed7e0d3c2f051e4992bb893e8434e5f
Auth-os Token manager address: 0x7e9f62b32538255065681c24efd7a5947f258351

*****************************
*****************************
*****************************
```

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

No

---

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #1150

I try to reproduce the error in the sokol network without success
I think the crowdsale of the problem is using exec-id , and is not proxy
Here is the line where the logical decision is made

https://github.com/poanetwork/token-wizard/blob/2.0/src/components/stepFour/utils.js#L994

Can you checked @dennis00010011b ?
If you find a problem, can you make a comment with the steps to reproduce it?

Regards

### CODE REVIEW

**Comment by mariano-aguero** [comment]
I add a screenshot of the file
screenshot_20180924_174838

**Comment by dennis00010011b** [comment]
@mariano-aguero I can't reproduce it too  for Minted. 
But for Dutch file contains execution ID instead proxy address
screen shot 2018-09-24 at 1 57 43 pm

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> I can't reproduce it too for Minted.

I think is an old contract

> But for Dutch file contains execution ID instead proxy address

That is maybe a bug, for Dutch File must contain proxy address? Is ok that ?

**Comment by dennis00010011b** [comment]
@mariano-aguero 
video https://www.useloom.com/share/08d0ee96022a4f9695c89f7c75b500bb
I corrected step 2:
```
2. Execute commands:
  - git submodule update --init --recursive --remote
  - cp .env.example .env
  - npm run start
```

**Comment by mariano-aguero** [comment]
@dennis00010011b 

Can you check it again? 
Please try to test it in private mode with your browser

**Pull request merged**
