### PR TITLE
(Feature) Step 3 - CSV File Upload Improvements 

### LINKED ISSUE #1179: (Feature) Step 3 - CSV File Upload Improvements
- See https://github.com/poanetwork/token-wizard/pull/1172#issuecomment-429494074

- It should work like the CSV importing in Step 2: Meaningful errors and warnings, etc.

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #1179

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Validator detects incorrect minCap for line with incorrect maxCap

screen shot 2018-10-31 at 6 00 13 pm

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Warning message: if warning contains one error then the text should be in singular form '...  is wrong' (instead `... are wrong `)

screen shot 2018-10-31 at 6 03 07 pm

screen shot 2018-10-31 at 6 09 16 pm

**Comment by dennis00010011b** [comment]
@mariano-aguero 
If mincap is fractional then warning text should contains:
 - phrase `Actual value is ...`
 - word `integer` instead `number`

screen shot 2018-10-31 at 6 12 39 pm

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Why not  to add ta phrase `actual value is..`  to each  incorrect line in this  warning message if  it has already added in similar case with wrong mincap?

screen shot 2018-10-31 at 6 42 52 pm

**Comment by mariano-aguero** [comment]
@dennis00010011b 

All feedback reported was fixed, Greetings

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Error messages are duplicated  if line has no minCap or maxCap

screen shot 2018-11-01 at 1 03 51 pm

screen shot 2018-11-01 at 1 08 02 pm

**Comment by mariano-aguero** [comment]
@dennis00010011b all errors belong to that line. Do you want the errors to be grouped by line?

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Follow messages are dublicates.  'The line number 5 need a minCap'  and  'The line number 5 has an incorrect mincap. Must be an integer. Actual value is empty'  
I think should be only one of them  (second)

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Follow messages are dublicates. The line number 5 need a minCap and The line number 5 has an incorrect mincap. Must be an integer. Actual value is empty
I think should be only one of them (second)

I did a simulation with your test file, I attached a capture.

screenshot_20181102_185258

**Comment by gabitoesmiapodo** [comment]
It seems to work fine.

I suggest a few changes:

1- It may be good to change

```
- The line number 1...
- The line number 2...
- The line number 3...

etc.
```

For a simpler and less cluttered

```
- Line #1... 
- Line #4...
- Line #6...

etc.
```

- I might be nitpicking, but I think that "Current value is..." is more adequate than "Actual value is..."

**Comment by mariano-aguero** [comment]
@gabitoesmiapodo 

Wording fixed here https://github.com/poanetwork/token-wizard/pull/1207/commits/d7bfa0fc477f47ad41d641b220cce66c571bab75

Greetings

**Pull request merged**
