### PR TITLE
(UI bug) Unfriendly warning at the landing page

### LINKED ISSUE #1139: (UI bug) Unfriendly warning at the landing page
It is not user-friendly to display sweet alert at the landing page of TW:

Let's remove any types of warnings from the landing page.

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #1139

Todo:

- Remove warnings from home
- Create crowdsales list section (issue created for desing #1145)
- Apply refactoring to stepOne and Home
- Added tests and updated snapshots

How to test it:
- Disable nifty wallet and load the page, go to the home section
- Go to step one, in the step one section a warning must be displayed
- Go to the crowdsales section, a warning must be displayed in this section

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Bottom of crowdsale list is empty
Chrome Version 69.0.3497.92 (Official Build) (64-bit)

screen shot 2018-09-18 at 11 48 43 am

**Comment by dennis00010011b** [comment]
@mariano-aguero 
unfriendly warning still here if a wallet not installed
screen shot 2018-09-18 at 11 57 53 am

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Bottom of crowdsale list is empty

There is an issue #1145 for this

> unfriendly warning still here if a wallet not installed

This warning must exist in the stepOne section and in the crowdsales list section

**Comment by fernandomg** [comment]
@mariano-aguero 

After closing the modal with the warning message the user remains in the `StepOne` screen. Maybe it will be better if it redirects to the `Home` screen, to prevent any possible inconsistent state if the user thinks to continue from there.

And there's no option selected by default
image

**Comment by fernandomg** [comment]
@mariano-aguero In regard to tests

Some of the snapshots for this tests are just `null`:
	- `Crowdsales/index.spec.js`
	- `Home/ChooseCrowdsale.spec.js`
	- `Home/CreateCrowdsale.spec.js`

Maybe `forceUpdate` is not necessary, if you can call enzyme's `wrapper.update()` instead, which will be calling `forceUpdate`

**Comment by mariano-aguero** [comment]
@fernandomg 

> After closing the modal with the warning message the user remains in the StepOne screen. Maybe it will be better if it redirects to the Home screen, to prevent any possible inconsistent state if the user thinks to continue from there.
And there's no option selected by default

Done

> Some of the snapshots for this tests are just null

Done

Have a nice weekend :)

**Comment by fernandomg** [comment]
@dennis00010011b If you can, give this PR a last review/approval. Thank you.

**Comment by dennis00010011b** [comment]
@mariano-aguero 
User can close sweet alert by clicking beside of it  3-4 times. As a result it isn't redirect to Home page if a wallet isn't installed 
https://www.useloom.com/share/c3c2dce05710439899583e31f1fb1b19

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Step 1: there's still no option selected by default if Wallet is installed and signed in

Done

> User can close sweet alert by clicking beside of it 3-4 times. As a result it isn't redirect to Home page if a wallet isn't installed

Done

**Pull request merged**
