### PR TITLE
(Feature) Implement new design for Step 1

### LINKED ISSUE #1085: Apply new design to Step 1 - CrowdsaleContract
Child of #1082

Designs:

https://zpl.io/bPYDOwm
https://zpl.io/2vYo8Je

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
**Description:**

Closes #1085 

Implementation of new designs for Token Wizard's step one.

Please let me know if I forgot something in this step.

**Designs:**

- https://zpl.io/bPYDOwm
- https://zpl.io/2vYo8Je

**Some screenshots**

mobile

tablet

desktop

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@gabitoesmiapodo 
Bottom half of screen empty if warning is present
screen shot 2018-09-11 at 9 32 40 am

Google Chrome version 68.0.3440.106 (Official Build) (64-bit)
MacBook Pro Retina

**Comment by gabitoesmiapodo** [comment]
@dennis00010011b fixed.

**Comment by gabitoesmiapodo** [comment]
@vbaranov fixed.

**Comment by fernandomg** [comment]
- component name changed from `stepOne` to `StepOne`
- Tests for:
  - `StepOne`
  - `StepNavigation`
  - `CheckIncompleteDeploy`
  - `removeTrailingNUL`
  - `toBigNumber`
  - `objectKeysToLowerCase`
  - `validateTier`
  - `validateSupply`
- Minor fixes

**Pull request merged**
