### PR TITLE
(Feature) Consider download contract info zip file from manage page

### LINKED ISSUE #627: (Feature) Consider download contract info zip file from /manage page.
**Problem**: If a user didn't download summary crowdsale file for any reason (error in deployment stage, for example), it is impossible to do from anywhere. Relates to https://github.com/poanetwork/token-wizard/issues/422#issuecomment-366747098.

**Solution**: 
- add a number of release to token wizard crowdsale contracts
- store releases numbers in `Registry` contract for every crowdsale 
- get source codes from crowdsale smart-contracts repository
- add button to download the summary file from management page

### PR DESCRIPTION
**Pull request by fernandomg**
Closes #627 

In this PR besides moving all the `downloadCrowdsaleInfo` to its own utility file, I took the opportunity to refactor it a bit so it's a bit easier to maintain/extend.

Also did the following fixes:
 - For minted-capped strategy, if there was one tier with _whitelist_ enabled, all tiers rendered the whitelist table header.
 - For minted-capped strategy, `minCap` wasn't rendered in non-whitelisted tiers.
 - For both strategies, `global minCap` is rendered only for dutch-auction strategy.
 - Used box-drawing chars for the tables
 - Made files more consistent in structure and spaces

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@fernandomg 
Minted - Manage page: downloaded file `MintedCappedCrowdsale_data.txt` contains incorrect info:
 1. Crowdsale end time
 2. Crowdsale hard cap (last tier's hard cap instead total hard cap)

Paameters of crowdsale: minted , 2 tiers, start/end time by default, no whitelist

screen shot 2018-10-14 at 11 43 54 am

**Comment by dennis00010011b** [comment]
@fernandomg 
Crowdsale parameters: Minted, 2 tiers, no whitelist, both tiers modifiable
Min cap value in file `002_tier.txt` changed after modifying mincap for tier #1

screen shot 2018-10-14 at 12 04 01 pm

**Comment by dennis00010011b** [comment]
@fernandomg 
Whitelist's table is messed in file `###_tier.txt`
There are extra symbols `\n` and  `,`

screen shot 2018-10-14 at 12 29 02 pm

Device: MacBookPro, MacOS, High Sierra 10.13.6

**Comment by fernandomg** [comment]
@dennis00010011b,

 - Crowdsale global values where fixed (`total supply` and `end time`)
 - Whitelist table layout fixed
 - For tier `n>1`, `min cap` is properly updated.
 - And if the `save` button was enabled, clicking on `Download` triggers `save` action. That was fixed as well.

**Comment by dennis00010011b** [comment]
@fernandomg 
`Auth-os_addresses.txt`  file : double lines for  Auth-os SaleManager address, Auth-os TokenManager address

screen shot 2018-10-16 at 10 24 01 am

**Comment by dennis00010011b** [comment]
@fernandomg 
Should encoded ABI parameters be changed if crowdsale's start/end time was changed? They aren't updated in file

**Comment by fernandomg** [comment]
> Should encoded ABI parameters be changed if crowdsale's start/end time was changed? They aren't updated in file

@dennis00010011b you can check, from the following block that the ABI params do not depend on those values:
https://github.com/poanetwork/token-wizard/blob/2.0/src/components/stepFour/utils.js#L64-L76

**Comment by fernandomg** [comment]
> Auth-os_addresses.txt file : double lines for Auth-os SaleManager address, Auth-os TokenManager address

Fixed. Thanks for that catch

**Pull request merged**
