### PR TITLE
(Bug) Dutch -Step3: allowed to add whitelist if the supply field is empty

### LINKED ISSUE #1233: (Bug) Dutch -Step3: allowed to add whitelist if the supply field is empty
Steps for reproduce:
 1. Start to create Dutch crowdsale
 2. Proceed to Step 3
 3. Leave field `supply` empty and enable whitelist

Expected result: 
 - button `Enable whitelisting Yes` should be disabled if field `supply` is empty (as it works for minted strategy)

Actual result:
 - possible to add whitelist if supply value isn't defined

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*localhost*

### If you were able to create it, what is the URL of your crowdsale?

*n/a*

### Do you have screenshots showing the problem?

screen shot 2018-11-24 at 15 13 21

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*no*

---

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #1233

### CODE REVIEW

**Comment by mariano-aguero** [comment]
@dennis00010011b 

Check if this issue #1183 is reproducible in this branch.

If this is solved, I think we should close that issue.
The design branch will replace the branch 2.0 in the next days and it is not worth the effort to solve it in the branch 2.0

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Still possible to add whitelist without supply
Steps:
 1. Go to Step3
 2. Fill out Supply
 3. Enable whitelist
 4. Clear Supply
 5. Add whitelist

 Expected result:
 - if supply  empty then  whitelist container should disappear  and whitelist enabled flag should be No (see how it works for  Minted startegy)

screen shot 2018-11-26 at 08 28 42

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Possible to add whitelist if  tier's  supply more than total supply and error warning is displayed
screen shot 2018-11-26 at 09 33 24

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Possible to add whitelist if tier's supply more than total supply and error warning is displayed

Fixed

**Pull request merged**
