### PR TITLE
(Feature) Allow minCap modification from manage page

### LINKED ISSUE #961: (Feature) Management page: global min cap per tier basis
**Problem**: min cap is global for crowdsale now. Auth-os introduced min cap per tier basis.

**Solution**: let's move global min cap property to every tier block. To update global min cap on a tier we should use this function: https://github.com/auth-os/applications/blob/master/TokenWizard/crowdsale/MintedCappedCrowdsale/contracts/classes/sale_manager/SaleManager.sol#L239

### PR DESCRIPTION
**Pull request by fernandomg**
Closes #961 

Work for both Minted Capped and Dutch Auction strategies.

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@fernandomg 
Issues that are not related minCap:
1. Incorrect value of maxCap for whitelisted.  minCap is displayed instead
2. button "Finalize " is active after finalization
screen shot 2018-06-22 at 14 28 07

**Comment by dennis00010011b** [comment]
@fernandomg 
minCap modification disabled after start of crowdsale. Should be enabled?
screen shot 2018-06-22 at 14 42 06

**Comment by dennis00010011b** [comment]
@fernandomg 
Issue are not related minCap: end time isn't updatable, transaction isn't created
screen shot 2018-06-22 at 14 55 53

**Comment by dennis00010011b** [comment]
@fernandomg 
minCap field should be disabled if whitelist is enabled
screen shot 2018-06-22 at 15 12 06

**Comment by dennis00010011b** [comment]
@fernandomg 
Multitier crowdsale: 2nd tier's minCap should be modifiable.
screen shot 2018-06-22 at 15 41 56

**Comment by dennis00010011b** [comment]
@fernandomg 
DutchAuction: manage page should contain minRate, maxRate info
screen shot 2018-06-22 at 16 12 47

**Comment by fernandomg** [comment]
@dennis00010011b 
> mincap isn't modifiable for Dutch, transaction isn't created

thanks for that catch. Fixed

**Comment by dennis00010011b** [comment]
@fernandomg 
Dutch: minCap is modifiable even if tier has started
`0x919fec4d504f9dbb32d914d1adcec3c99129a26000ad97ee049e0075bdd1a0cd `, Ropsten
screen shot 2018-06-26 at 07 43 16

**Comment by fernandomg** [comment]
> Dutch: minCap is modifiable even if tier has started

@dennis00010011b indeed. Auth-OS contract allow it. If this must behave as in Minted Capped strategy, then we should inform that.

@vbaranov ?

**Comment by vbaranov** [comment]
@fernandomg @dennis00010011b yes, it is correct, min cap is modifiable for ongoing crowdsale.

**Pull request merged**
