### PR TITLE
(Bug) Keep data between the steps (Step 1)

### LINKED ISSUE #1033: (Bug) Keep data between the steps
As a user, I want the application to keep the data until the end and allow me to go back, keeping the data between the steps.

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Ropsten

### If you were able to create it, what is the URL of your crowdsale?

None

### Do you have screenshots showing the problem?

None

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

None

---

### PR DESCRIPTION
**Pull request by mariano-aguero**
This is an integration PR for the step 1.
How to test it and what to test:
- Go to the home
- Create a crowdsale
- In the first step, press button "New crowdsale"
- Select the type of strategy
- Go to the second step
- Go back to step 1
- Should keep the selected strategy
- Refresh the step 1 page
- Should keep the selected strategy
- Go to the home, and press button "New crowdsale"
- The selected strategy must be the default, "WHITELIST WITH CAP"

The branch 2.0-integration must not be closed
Next steps to integrate:

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Minted-Manage page: 1 extra tier is rendered after each refreshing of page
Steps:
1. Create Minted crowdsale with 1 tier, any parameters
2. As an owner open manage page.
3. Refresh page, observe number of tiers
 
screen shot 2018-08-06 at 08 13 48

**Comment by mariano-aguero** [comment]
Hi @dennis00010011b 
Changes are added to an integrating branch. I did this, so we can focus on step-by-step issues that may arise. Then, when all steps are tested/approved, we should make a full test before merging to `2.0` branch.
For that particular issue you're mentioning, it gets duplicated because in the `Contribute` page the app is pushing tier data on every refresh, instead of cleaning it up.
I'll be working on that particular step in the next days.

Cheers

**Comment by mariano-aguero** [comment]
@fernandomg Fix applied and suggested refactoring

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Dutch: data lost after refreshing if supply value wasn't  touched (left by default)
Steps:
1. Select Dutch
2. Go to Step2
3. Fill out name, ticker with valid data
4. Refresh page, observe fields name, ticker

Expected result: fields name, ticker should keep the data
Actual result: fields name, ticker are empty

https://www.useloom.com/share/6b2ec15494f44ef599fdb834bcd0199d

**Comment by mariano-aguero** [comment]
Updated with changes from branch 2.0

**Comment by vbaranov** [comment]
@mariano-aguero please get upstream from 2.0 branch

**Comment by vbaranov** [comment]
@dennis00010011b Some e2e tests failed in CI. Is the problem with the tests itself, or the failures are caused by the changes from this PR?

**Comment by dennis00010011b** [comment]
@vbaranov @mariano-aguero 
Tests are good. There is problem with manage page: tiers are rendered twice
screen shot 2018-08-21 at 9 00 53 am

**Comment by mariano-aguero** [comment]
Hi @dennis00010011b 
I'm working in the manage section in another PR. I still have to push the changes

**Pull request merged**
