### PR TITLE
(Fix) Remove token/sale managers contracts for Dutch Auction

### PR DESCRIPTION
**Pull request by vbaranov**
Remove token/sale managers contracts for Dutch Auction. They are deprecated in the current implementation of Aut-os applications for TW. It fixes display of management page in local deployment. It is necessary for e2e tests.

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@vbaranov 
Dutch: minCap isn't initialized, always zero
`0xa3ce4e92d421bfb56e7cbb04b84e268a746a49f0b1636735d2aadaa8617f78d5`, Ropsten
screen shot 2018-06-26 at 07 14 53

**Comment by dennis00010011b** [comment]
@vbaranov 
Dutch with whitelist, Manage page: spontaneous error, page slow and unresponsive
`0x2aa6e2d3398348e4b6ee41cca7d9b65943e4ffddf7cfca3d1cde2a98e1a0a9b5`, Ropsten
screen shot 2018-06-26 at 07 25 05

[manageError.log](https://github.com/poanetwork/token-wizard/files/2137543/manageError.log)

**Comment by fernandomg** [comment]
> Dutch with whitelist, Manage page: spontaneous error, page slow and unresponsive

@dennis00010011b that error exist in `2.0` since a long time ago. It was fixed along with the changes in #973

**Comment by fernandomg** [comment]
> Dutch: minCap isn't initialized, always zero

@dennis00010011b That was fixed in #973 as well

**Pull request merged**
