### PR TITLE
(Feature) Apply new design to Crowdsales List / Manage Section

### LINKED ISSUE #1091: Apply new design to Manage page
Child of #1082

### LINKED ISSUE #1145: Apply new design to crowdsales list
Child of #1082

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #1145 
Closes #1091 

**Description**

New styles for Crowdsales' List and Manage Crowdsale sections.

**Some Screenshots**

Crowdsales List:

localhost_3000_manage_0x787c67b858fc7f7395cbd0837b4536d010e85499 laptop with mdpi screen
localhost_3000_crowdsales ipad
localhost_3000_crowdsales nexus 6p

Manage Crowsale:

- The "Crowdsale Page" link is not in the same place than in the design because it is not possible to do that currently using that "Title / Description" component, and because I think the link would get lost there from an usability point of view.
- There's no responsive / mobile design for this section, so I took some decisions along the way.

Dutch Auction:

localhost_3000_manage_0x787c67b858fc7f7395cbd0837b4536d010e85499 ipad
localhost_3000_manage_0x787c67b858fc7f7395cbd0837b4536d010e85499 laptop with mdpi screen 1
localhost_3000_manage_0x787c67b858fc7f7395cbd0837b4536d010e85499 nexus 6p

Whitelist With Cap:

localhost_3000_manage_0x787c67b858fc7f7395cbd0837b4536d010e85499 laptop with mdpi screen 2
localhost_3000_manage_0xbf0cee5e86a1d95eca9d0bf97cd3786abd21c989 ipad
localhost_3000_manage_0xbf0cee5e86a1d95eca9d0bf97cd3786abd21c989 nexus 6p

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@gabitoesmiapodo @mariano-aguero 
Since the manage page is accessible for users around the world then it needs to specify the time zone for start/end times. Time format could be like on Publish page, converted to UTC+0000

screen shot 2018-11-28 at 12 37 51

**Comment by dennis00010011b** [comment]
@gabitoesmiapodo @mariano-aguero 
Need remove reserved tokens block for non-owners accounts
screen shot 2018-11-28 at 12 45 46
Related https://github.com/poanetwork/token-wizard/issues/811

**Comment by gabitoesmiapodo** [comment]
@dennis00010011b 

Since development of TW is halting for now (see https://medium.com/poa-network/farewell-token-wizard-2-0-time-to-reprioritize-8cbd7319a97b), I think we need to keep this issue / PR exclusively for the rebranding / visual style related work.

Please create separate issues for any new business logic related problems you may find, as these problems still exist and we or anyone else might fix them in the future.

I've created issues for https://github.com/poanetwork/token-wizard/pull/1237#issuecomment-442597860 and https://github.com/poanetwork/token-wizard/pull/1237#issuecomment-442601795 : https://github.com/poanetwork/token-wizard/issues/1239 / https://github.com/poanetwork/token-wizard/issues/1238

If there aren't any more visual / UI problems and we have your approval for this PR we will proceed to merge it and finish this part of the job.

**Review by dennis00010011b — APPROVED** [review]

**Comment by mariano-aguero** [comment]
LGTM, added some improvements in another issue
https://github.com/poanetwork/token-wizard/issues/1240

**Review by mariano-aguero — APPROVED** [review]

**Comment by mariano-aguero** [comment]
I will merge this branch when the issue #1230 be approved

**Pull request merged**
