### PR TITLE
(Fix) crowdsale config should support exec-id and address of proxy as well

### LINKED ISSUE #1045: (Fix) crowdsale config should support exec-id and address of proxy as well
**Problem**: [crowdsale config](https://github.com/poanetwork/token-wizard/wiki/Token-Wizard-crowdsale-Configuration) doesn't support both: proxy address and exec-id

**Solution**: reorganize crowdsale config to support exec-id and address of proxy as well

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #1045

### CODE REVIEW

**Comment by vbaranov** [comment]
@mariano-aguero please get upstream from 2.0

**Comment by mariano-aguero** [comment]
@vbaranov 

> please get upstream from 2.0

Updated from the upstream

**Comment by vbaranov** [comment]
@mariano-aguero please resolve merging conflicts

**Comment by mariano-aguero** [comment]
@vbaranov Conflicts resolved

**Pull request merged**
