### PR TITLE
(Fix) Replace getCurrentTierInfo with getCrowdsaleTier for minted capped strategy

### LINKED ISSUE #1012: (Fix) Replace getCurrentTierInfo with getCrowdsaleTier for minted capped strategy
**Problem**: `getCurrentTierInfo(...)` function for minted capped crowdsale strategy strongly depends on `block.timestamp`, so, it changes not continuously. This leads returning of incorrect data for a tier until new block will be issued.

**Solution**: Instead, the suggestion is to add a function, that will calculate the current tier index (by iterating through [getTierStartAndEndDates](url) data for every tier) and then will call [getCrowdsaleTier](https://github.com/auth-os/applications/blob/2788cb547122b4fdfc3952037f7cad807c92abe5/TokenWizard/crowdsale/MintedCappedCrowdsale/contracts/MintedCappedIdx.sol#L451) function with this index

Note:
The number of tiers can be retieved with [getTiersLength](https://github.com/poanetwork/token-wizard/blob/2.0/src/components/crowdsale/utils.js#L270) function

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #1012 

- Added function getCurrentTierInfoCustom to replace actual getCurrentTierInfo
- A refactoring was performed in the contribute and manage sections

### CODE REVIEW

**Comment by mariano-aguero** [comment]
Hi @dennis00010011b , 
I was able to corroborate the test case with ganache successfully. I make some modifications in the function that returns the tier to solve the problem,  could you check it? Thank you

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Minted:1 tier, no whitelist, decimals=18, rate=1000, supply=200, minCap=13, duration 4 min:
 - Crowdsale page:  incorrect rate value
 - Contribution page: incorrect minContribution value (0.00416 instead 13)
 - Contribution page: incorrect maxContribution value  (13 instead 200)
- Investor can't buy, all transaction failed

screen shot 2018-07-25 at 01 00 19

**Comment by dennis00010011b** [comment]
@mariano-aguero
Tested with ganache
Minted:1 tier, no whitelist, decimals=18, rate=1000, supply=200, minCap=13, any duration:

 - Investor can't buy, all transaction failed
 - Error message in console

[localhost-1532507393317.log](https://github.com/poanetwork/token-wizard/files/2227132/localhost-1532507393317.log)

screen shot 2018-07-25 at 01 26 41

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Tested with ganache
Dutch: no whitelist, decimals=18, totalSupply=1000, supply=1000 , minRate=100, maxRate=200, minCap=13, duration by default:

 - Contribution page: incorrect minContribution value (1e-18 instead 13)

screen shot 2018-07-25 at 01 54 35

**Comment by mariano-aguero** [comment]
- The object returned by the getCurrentTierInfo method is different from the object returned by the method getCrowdsaleTier, 
so I had to generate an object that maintains the original properties of the tier.
- Conflicts resolved by pulling branch 2.0 changes

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Right, https://github.com/poanetwork/token-wizard/issues/1055 isn't reproducible in  branch `issue#1012`

**Comment by vbaranov** [comment]
@mariano-aguero I think we need to wait for @fernandomg voice for this PR, as he was starting working on this issue before.

**Pull request merged**
