### PR TITLE
(Feature) display max contribution limit for a whitelisted user in contribution page

### LINKED ISSUE #1027: (Feature) Display max contribution limit for a whitelisted user in contribution page
**Problem**: if a contributor is whitelisted he/she is unable to see what is the max amount of tokens he/she can buy from the contribution page.

**Solution**: add `Maximum contribution` field in case of a whitelisted user for both strategies in contribution page. I guess this extra field could be on the same line, that `Minimum contribution` field.

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #1027 

- Added max contribution limit in a " human-readable " way in the contribution section

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Contribution page - Minted, no whitelist:  min contribution value didn't changed after purchase

screen shot 2018-07-17 at 07 17 22

**Comment by mariano-aguero** [comment]
@dennis00010011b   
Currently that value does not change, depending on the business rule should it change? 
Is it a value that only serves to inform the user and should remain constant? 
If it should change then I suggest creating another issue since it has nothing to do with the original, and 
please specify how that field should change (A real example will help)
Thanks

**Comment by mariano-aguero** [comment]
@dennis00010011b 
As it currently works, the min contribution applies to all transactions, if that is not the case, another issue should be created and we must change that. 
Regards

**Comment by dennis00010011b** [comment]
@mariano-aguero 
 The min contribution is not  applied to all transactions, only to first transaction for each account.
It is current implementation in branch 2.0

**Comment by dennis00010011b** [comment]
@mariano-aguero 
``` 
Currently that value (min contribution) does not change, depending on the business rule should it change?
Is it a value that only serves to inform the user and should remain constant?
```
Min contribution field should display current min contribution value for given account( both whitelisted or minCap case )
Example: minCap =13
 1.Account hasn't bought yet ,  min contribution field  = 13
 2. Account has bought  amount =13,  min contribution field  = 0.000001 (real value depends of decimals).

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Dutch Auction: 
1. `min contribution` field is not changed after purchase
2. Minor GUI issue in field `max contribution`
screen shot 2018-07-17 at 08 30 09

**Comment by mariano-aguero** [comment]
Thanks @dennis00010011b for your explanation. I really appreciate it

> Minor GUI issue in field max contribution

Moved the block down, long data placed horizontally bring these kinds of problems

> min contribution field is not changed after purchase
I change the function that calculate the min contribution field, use the old one right now

**Comment by dennis00010011b** [comment]
@mariano-aguero 
I think fields `max contribution` and `min contribution` should be the same  and contains the text "You are not allowed"   when user is not allowed to buy
screen shot 2018-07-17 at 10 31 52

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> I think fields max contribution and min contribution should be the same and contains the text "You are not allowed" when user is not allowed to buy

Done

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Steps:
1. Create Minted crowdsale with  1 whitelist address
2. As  whitelisted investor buy maximum amount in first transaction
3. Refresh page
screen shot 2018-07-17 at 12 34 09

**Comment by mariano-aguero** [comment]
Hi @dennis00010011b 
I added a function to check if a crowdsale is really end for the logged user, is used to validate the appearance of the suggested text.

Regards

**Comment by vbaranov** [comment]
@mariano-aguero please resolve merging conflicts

**Comment by vbaranov** [comment]
@mariano-aguero I approved. But in the future let's consider to reuse data from currentTierInfo, currentTierStatus etc. We make multiple calls to the same functions in smart-contracts for a single page.

**Pull request merged**
