### PR TITLE
(Fix) whitelists for both strategies fix

### PR DESCRIPTION
**Pull request by vbaranov**
Closes https://github.com/poanetwork/token-wizard/issues/966

Created on top of https://github.com/poanetwork/token-wizard/pull/968

Changes of whitelists interfaces are implemented

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@vbaranov 
Minted-Manage page: incorrect  max_purchase_remaining displayed for whitelisted addresses
should be 101, displayed 1000

screen shot 2018-06-20 at 07 44 44

**Comment by dennis00010011b** [comment]
@vbaranov
Minted-Manage page: whitelisted address is disappeared from the list after first purchase
screen shot 2018-06-20 at 08 11 12

**Comment by dennis00010011b** [comment]
@vbaranov 
Minted:  added from manage page whitelisted address can't buy.
ExecID: 0x45e010b9ae401e2eb71529478da8bd513a9bdc2d095a111e324f5b95c09ed87b, Ropsten
Reverted TX: https://ropsten.etherscan.io/tx/0x0bb218d50df1737802acbf76047a3b1e58d1fe99545409957a3c556ca6193b09
screen shot 2018-06-20 at 08 49 28

**Comment by dennis00010011b** [comment]
@vbaranov 
Minted-Manage page: Error message spontaneously appears after start of tier. 
Whitelisted container becomes disabled.
ExecID: 0x45e010b9ae401e2eb71529478da8bd513a9bdc2d095a111e324f5b95c09ed87b, Ropsten
Crowdsale parameters: Minted, 1 tier, modifiable, whitelisted, one whitelisted address was added after start of crowdsale.

screen shot 2018-06-20 at 09 02 11

[localhost-1529510543779qq.log](https://github.com/poanetwork/token-wizard/files/2120162/localhost-1529510543779qq.log)

**Comment by vbaranov** [comment]
@dennis00010011b I believe we should configure management page with the latest Auth-os registry version in a separate PR. Is this issue #966 is reproducible from this PR?

**Comment by dennis00010011b** [comment]
@vbaranov 
whitelisted investor can buy if whitelist was added before deployment
In the case if  whitelisted addresses added from manage page then they can't buy, see my comment above https://github.com/poanetwork/token-wizard/pull/971#issuecomment-398802609

**Comment by vbaranov** [comment]
@dennis00010011b 
>Minted: added from manage page whitelisted address can't buy.

I see "added from manage page", right? It is also related to the management page reconfiguration

**Comment by dennis00010011b** [comment]
@vbaranov 
Right. Purchase works well for whitelisted investor that was added before deployment. For both strategies.

**Comment by vbaranov** [comment]
@dennis00010011b
>Minted: added from manage page whitelisted address can't buy.
ExecID: 0x45e010b9ae401e2eb71529478da8bd513a9bdc2d095a111e324f5b95c09ed87b, Ropsten
Reverted TX: https://ropsten.etherscan.io/tx/0x0bb218d50df1737802acbf76047a3b1e58d1fe99545409957a3c556ca6193b09

it is fixed in this PR. Whitelist limits are in tokens are in tokens.

**Pull request merged**
