### PR TITLE
(Feature) deployment step: global min cap per tier

### PR DESCRIPTION
**Pull request by vbaranov**
Closes https://github.com/poanetwork/token-wizard/issues/962

screencapture-localhost-3000-3-2018-06-19-17_05_45

### CODE REVIEW

**Comment by fernandomg** [comment]
Also, if 1st tier `minCap` has a value, after enabling whitelist for the second tier... first tier minCap is set to `0` (zero)

**Comment by dennis00010011b** [comment]
Field minCap is always  empty. Possible cause could be that getCurrentTierInfo().tier_min returns value in tokens, not in wei.

Parameters:  1 tier, minCap, no whitelist, not modifiable. I used  this ` .env ` https://github.com/poanetwork/token-wizard/blob/874209ae06233b4c1de4b54c44717ca557795013/.env.example#L1

screen shot 2018-06-19 at 10 59 21

**Comment by dennis00010011b** [comment]
Manage page: whitelist container presents if duration_is_modifiable = true, whitelist_enabled  = false
Parameters: 1 tier, minCap, no whitelist, modifiable. I used new  ` .env ` https://github.com/poanetwork/token-wizard/blob/874209ae06233b4c1de4b54c44717ca557795013/.env.example#L1

screen shot 2018-06-19 at 11 31 48

**Comment by vbaranov** [comment]
@dennis00010011b the PR is for deployment step mainly. @fernandomg will continue changes for management page in frames of https://github.com/poanetwork/token-wizard/issues/961

**Comment by vbaranov** [comment]
@fernandomg fixed. Please take a look.

**Comment by vbaranov** [comment]
@dennis00010011b nevertheless I fixed this
>Field minCap is always empty. Possible cause could be that getCurrentTierInfo().tier_min returns value in tokens, not in wei.

**Comment by vbaranov** [comment]
@dennis00010011b @fernandomg are there any issues except problems with management page? there are a lot of changes in this PR. Next PRs will depend on it. I suggest to adjust management page for new interface of Auth-os iun a separate PR.

**Comment by dennis00010011b** [comment]
@vbaranov 
1. I can’t create multitier crowdsale. Transaction failed during deployment.
2. minCap initialization incorrect: if mincap=12 on Step3 then minCap =0,000000000000000012 in contracts
3. minCap is not modifiable (related manage page but anyway)

**Comment by dennis00010011b** [comment]
@vbaranov 
4. If allowModify is enabled (duration_is_modifiable=true) then any address is not allowed to buy
screen shot 2018-06-20 at 10 57 53

**Comment by dennis00010011b** [comment]
@vbaranov 
Extra tier is created. I created crowdsale with 2 tiers,  3 tiers were initializated 
screen shot 2018-06-20 at 15 27 30

**Comment by vbaranov** [comment]
@dennis00010011b 
>1. I can’t create multitier crowdsale. Transaction failed during deployment.
>2. minCap initialization incorrect: if mincap=12 on Step3 then minCap =12 in contracts and minCap =0,000000000000000012 tokens for investors
>4. If allowModify is enabled (duration_is_modifiable=true) then any address is not allowed to buy

Fixed

>1 .I created crowdsale with 2 tiers, 3 tiers were initializated . Extra tier is created.
Please post exec-id here.
>2. I still can't create crowdsale with 3 and more tiers.
I can't reproduce this. Is any error in Chrome dev console? Could you post the link to failed tx?

**Comment by vbaranov** [comment]
>1 .I created crowdsale with 2 tiers, 3 tiers were initializated . Extra tier is created.
>2. I still can't create crowdsale with 3 and more tiers.

I reproduced both. It is not broken with this PR. These are issues with Auth-os.

**Comment by vbaranov** [comment]
>1. I created crowdsale with 2 tiers, 3 tiers were initializated . Extra tier is created.

This is also fixed. Function logic to add tiers was changed from Auth-os side.

> 2. I still can't create crowdsale with 3 and more tiers.

It looks like a bug from Auth-os side.

I will merge this PR.

**Pull request merged**
