### PR TITLE
(Feature) Step 2 - CSV file upload improvements

### LINKED ISSUE #1149: (Feature) Step 2 - CSV file upload improvements.
Child of #1082

1- Even as it may seem obvious for an experienced user, it might be difficult for a newcomer to know how the CSV file for the 2nd step should be formatted.

It would be nice if we give the user the option to download a template / example file, similar to the attached example:

csv-template

2- It would also be good if we can provide some kind of feedback when an invalid CSV file is uploaded.

For example, see this screenshot for when I upload a random CSV file:

screen shot 2018-09-19 at 15 11 40

I think it would be better to let the user know there was an error, and also suggest him / her to check the file is OK, and to download the CSV template.

3- @dennis00010011b pointed out this https://github.com/poanetwork/token-wizard/pull/1148#issuecomment-422975566

> value of reserved tokens isn't rounded if it was downloaded from CSV file

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #1149

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@mariano-aguero 
If CSV file contains rows with the same address and dimension but different values then will be added only one address (which latest). In this case warning contains incorrect number of added addresses

Tested data:
```
0x95ced938f7991cd0dfcb48f0a06a40fa1af46ebc,tokens,3.1
0x95ced938f7991cd0dfcb48f0a06a40fa1af46ebc,tokens,4.2

```
Added 1 address, warning shows  2
screen shot 2018-09-29 at 1 23 06 am

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Warning doesn't contain number of imported addresses if more than 20 addresses were uploaded
Warning's text should contains phrase ' `Reserved tokens imported Tokens will be reserved for N addresses' 

screen shot 2018-09-29 at 1 39 27 am

**Comment by gabitoesmiapodo** [comment]
@mariano-aguero 

- Just a little issue (I don't know if this got to be fixed here, or in a new issue): if you upload an empty file you get a message "0 tokens imported blah blah".

I think it would be better to display some meaningful error when this happens, for example: "Empty CSV file. Nothing was imported.", or something like that.

screen shot 2018-10-01 at 09 50 26

- I fixed this mobile version's UI issue.

Before:

screen shot 2018-10-01 at 09 55 02
screen shot 2018-10-01 at 09 56 45

After:

screen shot 2018-10-01 at 10 07 44

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> If CSV file contains rows with the same address and dimension but different values then will be added only one address (which latest). In this case warning contains incorrect number of added addresses

Done

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Validator of uploaded CSV detects errors but there is no warning message in cases if :+1: 
typo in dimension unit
incorrect value (typo or negative)
numbers of column more than 3

Done

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Warning doesn't contain number of imported addresses if more than 20 addresses were uploaded
Warning's text should also contains phrase ' `Reserved tokens imported Tokens will be reserved for N addresses'

Done

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> I think it would be better to display some meaningful error when this happens, for example: "Empty CSV file. Nothing was imported.", or something like that.

Done

**Pull request merged**
