### PR TITLE
(Bug) Keep data between the steps (Manage Page)

### PR DESCRIPTION
**Pull request by mariano-aguero**
This is an integration PR for the manage section

How to test it and what to test:
- Go to the home
- Create a crowdsale (Minted or Dutch)
- Go to the home, choose the created crowdsale
- You should see the created crowdsale
- If you refresh the page, you should see the data again

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Step 1 - Choose crowdsale: list of crowdsales is shown  only for last used Network
Steps:  
 1. Set account which has already created crowdsales in Sokol and Ropsten networks.
 2.  For each network go to Step1-Choose crowdsale, observe list
In my case list empty for Ropsten
screen shot 2018-08-22 at 8 35 18 am

screen shot 2018-08-22 at 8 35 40 am

 3. Create any crowdsale in Ropsten network
 4.  For each network go to Step1-Choose crowdsale, observe list
Actual result: 
 - Sokol network:  list is empty 
 - Ropsten network:  list contains  previous created crowdsales
screen shot 2018-08-22 at 8 42 04 am
screen shot 2018-08-22 at 8 42 19 am

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Step1-Choose crowdsale: list should be sorted and show the same order after each opening
Now order of crowdsales sometime could be different after refreshing or re-opening page 
screen shot 2018-08-22 at 8 56 18 am

screen shot 2018-08-22 at 8 56 38 am

**Comment by mariano-aguero** [comment]
@dennis00010011b

> Step1-Choose crowdsale: list should be sorted and show the same order after each opening

Fixed in this branch, but I think is not related with this PR, see PR  #1046

**Comment by mariano-aguero** [comment]
@dennis00010011b 
 

> Step 1 - Choose crowdsale: list of crowdsales is shown only for last used Network

Can you check if the problem persist? if yes, can you make a video of the problem? The env vars for sokol are the same for ropsten? Thanks in advance

**Comment by dennis00010011b** [comment]
@mariano-aguero
Build failed to compile, got error:
`Failed to compile.
./src/components/stepFour/index.js
  Line 183:  'getNetworkVersion' is not defined  no-undef `

**Comment by dennis00010011b** [comment]
@mariano-aguero 
>Can you check if the problem persist? if yes, can you make a video of the problem? The env vars for sokol are the same for ropsten? Thanks in advance

 Problem https://github.com/poanetwork/token-wizard/pull/1103#issuecomment-415080605 still exist. Maybe would be better to make it as separate issue?
You can check with my account , PR `ba98116a7d4b98f22f113c59448b9cc69f916d75f35d51f088b64b483fd0b8ca`
 Video:
https://www.useloom.com/share/31c70da4928e47c29d7043eda4c30d6a

Contract's accounts are different for each network. 
.env file:

`REACT_APP_ABSTRACT_STORAGE_ADDRESS='{"3":"0x0648b0645574966c32d37bc5be0208a979342677","77":"0x9d126f44151f70a4da03f53fcb485dea6c0b8d64", "42": "0x2b2d1b6867572ed42140b11b2dac7d454bbce73d", "4": "0xb5bfd08585b705c0eec3c9043249902cc9291ad8","99":"0xd70befce3cf1cc88119c8f4eb583ccd4c39d06e2"}'
REACT_APP_REGISTRY_IDX_ADDRESS='{"3":"0x417f7d0f10fc18c6e139c06e0db7634b5d5756f4","77":"0x76fafe6f7e2f25e40664cf9f22d6e18b709d0087", "42": "0x1be7505450bcd62b2001db8eefb9be1706db45c6", "4": "0xf9d9365d93a351ea4f9ee712a3b731e1d6440a59","99":"0xda7cd8385be8f293677574925f35fbeb38c35a85"}'
REACT_APP_PROVIDER_ADDRESS='{"3":"0xc8bdff0860cc2d0c349208f79e0f3e086effe0cb","77":"0x663d2feb6af69867e0144aab82624edb7af1728b", "42": "0x11bd7d75c081ae7deb9244981a72ceeb340bcbc1", "4": "0x8ca673abb1123a3ffe4000bc813ae2c00d0c7c02","99":"0xef5879ad4ba3fa0312875426902dd384d8c63fcd"}'
REACT_APP_REGISTRY_EXEC_ADDRESS='{"3":"0x1e2f3f5e8022cf28804dd69b81629927079f9951","77":"0x6865f64ecb1f0222a0febe5c1fc1b40c7a378da6", "42": "0xef4dc7adb5d13448597e4d4b471b66c4690568d2", "4": "0x13462c0292f3007ee6d0aaf600dbe1db2ebcf4be","99":"0xd7a4deeeb59569a9d00ba78a18d591bfe53807e0"}'
REACT_APP_MINTED_CAPPED_IDX_ADDRESS='{"3":"0x21712e030328541ba8a1d044df0317047dd76bb9","77":"0xeeaefd3a69f7d10db92205bbaa54f7c5aa8edf3f", "42": "0xa32057752831f4cc0cc49e7f74bb3cd67237af00", "4": "0xd504e3fb278d36437023fbcdcfd9dd194c71c6c2","99":"0x6f1b623058ffe30b14a6071bbbecaa373cef20c8"}'
REACT_APP_MINTED_CAPPED_CROWDSALE_ADDRESS='{"3":"0x9039d36603b92211d2532f7f4ecbeced912172bb","77":"0x1d9702eb87c47f90c8669f3d36322f8cf985f721", "42": "0x3397eef245bd419b9e8cc5bc20e896ff784e6d5d", "4": "0xef4dc7adb5d13448597e4d4b471b66c4690568d2","99":"0x39b586af1b947a31806406d8e7dca12240e149eb"}'
REACT_APP_MINTED_CAPPED_CROWDSALE_MANAGER_ADDRESS='{"3":"0x10df208e0b76a4e9f8b54e436022f113d4bae5c3","77":"0x3ab54a53eed7e0d3c2f051e4992bb893e8434e5f", "42": "0xf9d9365d93a351ea4f9ee712a3b731e1d6440a59", "4": "0xefc62352f46c62b8aab3d1a802c0c54fc320130b","99":"0x3f099bd191c3f38d60088c287b18f91b1a84f972"}'
REACT_APP_MINTED_CAPPED_TOKEN_ADDRESS='{"3":"0x7b0ab844e92ce6ac36cc844e452766fa11a48c82","77":"0xbe1efbd9134bb5cd0ad3ee6cd2c246e56961ac5c", "42": "0xb5bfd08585b705c0eec3c9043249902cc9291ad8", "4": "0xf0e295c8c1947e834ade8fd3742f51ac44fccba9","99":"0xebd4f6ef12688a35406198ae2a39934fc70e3378"}'
REACT_APP_MINTED_CAPPED_TOKEN_MANAGER_ADDRESS='{"3":"0x0a019b617a0e1745494e9f5dbefdd82445fd9035","77":"0x7e9f62b32538255065681c24efd7a5947f258351", "42": "0x8ca673abb1123a3ffe4000bc813ae2c00d0c7c02", "4": "0xa4fec065faa308a08dba10373e78a04ea5cc5117","99":"0x001aed057cb44ff7325d990db3ff69b0761cccab"}'
REACT_APP_DUTCH_IDX_ADDRESS='{"3":"0x6d7b8d8b819dfb3b03b1a9b1c376f409f48e11f4","77":"0xfbb8127eeb14be7305a6738aa9e43654a95ad908", "42": "0x13462c0292f3007ee6d0aaf600dbe1db2ebcf4be", "4": "0xd1ad7938b170fd9f79221497178b5abc68924d34","99":"0xcb5e9ded56c9fbf4a309f2d6f4e1bbbeb4e31bf7"}'
REACT_APP_DUTCH_CROWDSALE_ADDRESS='{"3":"0x9c5f8263171b83c303c18b7b1977fa28bdd45116","77":"0x3f52577e2772f0adacd9d3e6a0fdb456701bf386", "42": "0x1c6d46dedd61ef982f0938e73975404b8de6d739", "4": "0xd37bfd3632f78608ad82d1a8c253e2b35908e35f","99":"0x729b907b2e4ff8d150bc774f400a3afe4553b468"}'
REACT_APP_DUTCH_TOKEN_ADDRESS='{"3":"0xd1A26D4A869d66EEeA894c47b5d4F0B3A6FC6cAb","77":"0x2a5fbbb4ec592bace485d0f653b051d991eeffdc", "42": "0xf188df9b40f5a5598a1d7088021a679312e62d03", "4": "0x4b34e3df0b4803674db01b0eaef937e6022f4610","99":"0x9f057f47e10b1d58ce2531863597d9dc992df07a"}'
REACT_APP_TW_PROXIES_REGISTRY_ADDRESS='{"3":"0xf8141d3ef4ca940d0f485d0abbf2b11e6303c484","77":"0x16a3e07d364d410c6c99e82047177e604779eb02", "42": "0x7cbe84100ff284f87ecd4d5830ff788b9a7ce49e", "4": "0xd836f5716217640ab97bd6ee848881c42625a05d","99":"0xc6468767214c577013a904900ada0a0dd6653bc3"}'
REACT_APP_PROXY_PROVIDER_ADDRESS='{"3":"0x7ae09e9963c835959b06240ba69b00febdff681a","77":"0x7ae09e9963c835959b06240ba69b00febdff681a", "42": "0x7ae09e9963c835959b06240ba69b00febdff681a", "4": "0x7ae09e9963c835959b06240ba69b00febdff681a","99":"0x7ae09e9963c835959b06240ba69b00febdff681a"}'
REACT_APP_REGISTRY_EXEC_ID='{"3": "0xb10e2d527612073b26eecdfd717e6a320cf44b4afac2b0732d9fcbe2b7fa0cf6", "77": "0xb10e2d527612073b26eecdfd717e6a320cf44b4afac2b0732d9fcbe2b7fa0cf6", "42": "0xb10e2d527612073b26eecdfd717e6a320cf44b4afac2b0732d9fcbe2b7fa0cf6", "4": "0xb10e2d527612073b26eecdfd717e6a320cf44b4afac2b0732d9fcbe2b7fa0cf6","99":"0xb10e2d527612073b26eecdfd717e6a320cf44b4afac2b0732d9fcbe2b7fa0cf6"}'
REACT_APP_MINTED_CAPPED_APP_NAME='MintedCappedCrowdsale'
REACT_APP_DUTCH_APP_NAME='DutchCrowdsale'
REACT_APP_MINTED_CAPPED_APP_NAME_HASH='0x4d696e74656443617070656443726f776473616c650000000000000000000000'
REACT_APP_DUTCH_APP_NAME_HASH='0x447574636843726f776473616c65000000000000000000000000000000000000'
REACT_APP_INFURA_TOKEN='kEpzZR9fIyO3a8gTqJcI'
`

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Build failed to compile, got error:

Done

> Problem #1103 (comment) still exist. Maybe would be better to make it as separate issue?

Agree to generate a separate issue for this

**Comment by dennis00010011b** [comment]
@mariano-aguero 
>Problem #1103 (comment) still exist. Maybe would be better to make it as separate issue?
Agree to generate a separate issue for this

Issue isn't reproducible in branch 2.0. It should be fixed before merge into 2.0

**Comment by mariano-aguero** [comment]
@dennis00010011b 

I think we can solve this in the integration branch, so we can merge this PR an make a progress

**Pull request merged**
