### PR TITLE
(Bug) Keep data between the steps (Step 3)

### PR DESCRIPTION
**Pull request by mariano-aguero**
This is an integration PR for the step 3.

How to test it and what to test:
- Go to the home
- Create a crowdsale
- In the first step, press button "New crowdsale"
- Select the type of strategy
- Go to the second step
- Go back to step 1
- Should keep the selected strategy
- Refresh the step 1 page
- Should keep the selected strategy
- Got to the second step
- Complete the form
- Refresh the page, should keep the data
- Add reserved tokens
- Refresh the page, should keep the data
- Got to the third step
- Complete the form
- Refresh the page, should keep the data
- Go to the home, and press button "New crowdsale"
- The selected strategy must be the default, "WHITELIST WITH CAP"
- Go to the second step
- The form must be empty

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Dutch-Step3: flag `burn excess` lost state after page refreshed
Steps:
1. Select Dutch, go to Step2
2. Fill out Step2 with valid data
3. Go to Step3
4. Set 'YES'  for checkbox `burn excess` 
5. Refresh page (or go back and forward), observe checkbox `burn excess`

 Actual result: 
  - checkbox `burn excess` doesn't keep data

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Dutch-Step3: warnings are not displayed after refresh
Steps:
1. Select Dutch
2. Fill out forms in Step2 with valid data
3. Go to Step 3
4. Enter any invalid data in field MinCap(ex.-1232), warning should be displayed
5. Refresh page, observe field MinCap 
Try the same with fields Supply, start/end date, min/max rate, custom gasprice

Expected result: 
 - warnings sholud be dispalyed if data incorrect
Actual result: 
 - warnings are not displayed after refresh


screen shot 2018-08-14 at 06 40 57

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Duplicate declaration "logger"; line 15 ,21

Fixed in a previous commit, line included from a merge

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Dutch-Step3: flag burn excess lost state after page refreshed

Fixed

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Dutch: possible to add 2nd tier

Fixed

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Step3: incorrect placeholder for start/end time
Steps for reproduce:
 - proceed to Step3(doesn't matter Minted or Dutch)
 - observe start/end date fields
screen shot 2018-08-15 at 07 26 14

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Step3 page is unresponsive:
 - can't set checkbox, it leads to crash
 - can't fill out fields, it is delayed

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> incorrect placeholder for start/end time
no default values for checkboxes

> Step3 page is unresponsive

Update the repository, create a new crowdsale, it should work.
This behavior is due to the fact that the first tier was not initialized correctly and the storage has  inconsistent data
screenshot_20180815_122903

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Minted/Dutch-Step3: field supply disabled if switch whitelist from enabled to disabled
Steps:
1. Select Minted(or Dutch)
2. Proceed to Step 3
3. Fill out field Supply with valid value
4. Enable whitelist and add 1 address
5. Disable whitelist.
6. Observe field Supply

Expected result:
Field Supply should be enabled if no whitelist addresses or whitelist disabled
screen shot 2018-08-15 at 08 46 59

**Comment by mariano-aguero** [comment]
@dennis00010011b 


> Minted/Dutch-Step3: field supply disabled if switch whitelist from enabled to disabled

Fixed

> Minted/Dutch-Step3: warnings are not displayed after refresh

Fixed

> Dutch: possible to add 2nd tier

Fixed

Run test
screenshot_20180816_103949

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Tested it . No issues were found

**Comment by mariano-aguero** [comment]
@fernandomg 

> Another thing, the error message is wrong since always... as it should be >=0.1

Done

> I'm getting an error when Custom Gas Price is selected..

Fixed

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Step3-Custom gasprice: no error message if value = 0
Steps for reproduce:
1. Proceed to Step 3 
2. Set checkbox 'Custom gasprice'

Possible solution :  make default value 0.1 , not 0.
screen shot 2018-08-17 at 6 54 52 am

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Minted/Dutch-Step3: form is cleared if gasprice checkbox is changed
Steps:
1. Proceed to Step 3 with valid data
2. Fill out fields Supply, Rate, MinCap
3. Set checkboxes 'Allow modify', 'Whtelist enabled'
4. Set checkbox 'Normal' in section gasprice
5. Observe fields Supply, Rate, MinCap, checkboxes 'Allow modify', 'Whtelist enabled'

Actual result: fields empty, checkboxes in condition by default
https://www.useloom.com/share/f4328c5875a2405ca729f24a98fe157f

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Step3-Custom gasprice: no error message if value = 0

Change constant to 0.1

> Minted/Dutch-Step3: form is cleared if gasprice checkbox is changed

Fix how event is triggered

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Step3-Custom gasprice: no error message if value = 0

Done

> Minted/Dutch-Step3: form is cleared if gasprice checkbox is changed

Done

**Comment by mariano-aguero** [comment]
Updated with changes from branch 2.0

**Comment by dennis00010011b** [comment]
@mariano-aguero  
Tested. No issues were found.

**Pull request merged**
