### PR TITLE
(Feature) Proxy contracts files (.sol, .abi & .bin)

### LINKED ISSUE #1036: (Feature) add a script to generate flat source codes, ABI and binaries of Proxies smart-contracts
**Problem**: A part of https://github.com/poanetwork/token-wizard/issues/1035, metadata of Proxies is stored in `./public/contracts/` and it is static. The idea is to generate these metadata files from the source code at every Wizard deployment.

**Solution**: add a script, that will get flat source codes, ABI and binaries of Proxies smart-contracts (both: Dutch Auction and Minted capped crowdsale). 

From my perspective:
A script should have a config. This config should have a parameter to store a hash of commit in https://github.com/poanetwork/auth-os-applications repository (*note: this repo is already used in git submodules*). 
A script will start before deployment of Wizard and will:
 - get the source code of [Minted caped proxy](https://github.com/poanetwork/auth-os-applications/blob/master/TokenWizard/crowdsale/MintedCappedCrowdsale/contracts/MintedCappedProxy.sol) and [Dutch Proxy](https://github.com/poanetwork/auth-os-applications/blob/master/TokenWizard/crowdsale/DutchCrowdsale/contracts/DutchProxy.sol)
- generate flat source of proxies. Example of flattener could be gotten here: https://github.com/poanetwork/auth-os-applications/blob/master/TokenWizard/crowdsale/MintedCappedCrowdsale/scripts/flatten.sh
- save proxies source codes to `./public/contracts/` folder, into `MintedCappedProxy.sol` and `DutchProxy.sol` files
- compile smart-contracts with Truffle `truffle compile` and save ABI and binary code to `./public/contracts/` folder into `MintedCappedProxy.bin`, `MintedCappedProxy.abi` and `DutchProxy.bin`, `DutchProxy.abi` correspondingly

### PR DESCRIPTION
**Pull request by fernandomg**
Closes #1036 

A bash script was created to generate the files for the proxy contracts in TW, from source stored in submodule `auth-os-applications`
- To execute it with the current submodule commit:
  - `./scripts/generateProxyContracts.sh`
- To execute it from a particular commit in the submodule:
  - `./scripts/generateProxyContracts.sh 1234567`
  - where `1234567` is the commit hash

It was added as the last step in the build process (`npm run build`)

### CODE REVIEW

**Comment by vbaranov** [comment]
@fernandomg maybe, let's add it also to `npm run start` ?

**Comment by dennis00010011b** [comment]
@fernandomg 
In this PR scripts  for e2e tests don't work anymore : 
`npm run e2eMintedWhitelist, npm run e2eMintedMincap, npm run e2eDutchWhitelist, npm run e2eDutchWhitelist` because contract don't deployed. Could you please look at it?

**Comment by mariano-aguero** [comment]
@fernandomg 
There are problems when executing the transactions. The branch e2e, I think it is not properly updated (to use locally with ganache). With ropsten there is another error

Ropsten
screenshot_20180827_090414

Ganache
screenshot_20180827_083257

**Comment by fernandomg** [comment]
@mariano-aguero please check now. It should be working properly for `ropsten` and with `ganache`.

**Comment by dennis00010011b** [comment]
@fernandomg @mariano-aguero 
Now it works with Ropsten and ganache. But e2etests still failed 
https://travis-ci.org/poanetwork/token-wizard/builds/421193879?utm_source=github_status&utm_medium=notification

**Pull request merged**
