### PR TITLE
(Feature) add source code of Proxy smart-contract to Publish page

### LINKED ISSUE #1037: (Feature) add source code of Proxy smart-contract to Publish page
child of #1035 

**Solution**: The source code of Proxy smart-contract could be added in the textarea below all other properties of crowdsale, as it is done in `master` branch of Token Wizard (live link: https://wizard.poa.network/)

### PR DESCRIPTION
**Pull request by fernandomg**
Closes #1037 

I've just added sources for `.abi`, `.bin` and `.src`.

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@fernandomg 
Publish page: section `CROWDSALE PROXY CONTRACT CREATION CODE` contains **contract byte code**  (it matches ./public/contracts/MintedCappedProxy.bin in case of Minted crowdsale)

Should contains **contract creation code = contract byte code + constructor parameters**

**Comment by fernandomg** [comment]
@dennis00010011b Mh... It was intended to be the 'Contract Creation Code' for the proxy contract. And so far it looks that it's not necessary on the TW.

Also to find the 'Contract Creation Code' for an already deployed contract, I have to find the original `tx` when the Proxy contract was deployed, and gather the information from there (@dennis00010011b, @vbaranov please correct me if I'm wrong).

So I just leave only the `.abi` and `.src` content in the Publish page.

**Comment by vbaranov** [comment]
@fernandomg we need to give source code and ABI encoded parameters to a user. By having these set of parameters (with contract name and compiler version) a user will be able to verify Proxy smart-contract and will see ABI of it after verification. Addition of ABI encoded parameters is requested in #1038. Addition of source code is implemented here. Display of ABI is redundant. Let's remove it from Publish page.

**Comment by fernandomg** [comment]
@vbaranov thanks for the clarification, change done.

**Pull request merged**
