### PR TITLE
(Bug) Keep data between the steps (Step 4 - Publish && Step 5 - Contribution Page)

### PR DESCRIPTION
**Pull request by mariano-aguero**
@dennis00010011b 
Can you check this two steps with this branch?
I Perform some tests and it seems to work well, I would need your expert eye

Thanks in advance

### CODE REVIEW

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Probably it should be separate issue
Step4-deployment process: user able to change network and continue deployment
Steps for reproduce:
1. Set network 'Sokol' in Nifty wallet
2. Step 1: select Minted
3. Proceed through Step1-Step3  with valid data
4. Step4: confirm 2 transactions
5. Nifty wallet: switch network to  Ropsten

Expected result: 
 - should be warning which prevent from continue deployment
 - user won't able to continue deployment unless switch back to pristine network

Actual result:
 - user able to continue and finish deployment with other network

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Publish page: supply=0 is displayed for Minted strategy
Expected result:
 - supply value should be the sum of  all tier's maxCap  
screen shot 2018-08-17 at 1 47 38 am

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Crowdsale page: transaction is generated if user switch between Publish and Crowdsale pages
Steps:
1. Create Minted crowdsale with any valid parameters, proceed until Crowdsale page
2. Go back to Publish page
3. Click button 'Continue' and go forward to Crowdsale page
4. Observe Wallet, new transactions

Actual result: 
 - new transaction is generated each time when user switchs between  Publish and crowdsale pages

https://www.useloom.com/share/bca7bd600b6d406b9c13bcb70c28ac0a

**Comment by mariano-aguero** [comment]
Hi @dennis00010011b 

> Probably it should be separate issue
Step4-deployment process: user able to change network and continue deployment

Done in this branch

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Crowdsale page: transaction is generated if user switch between Publish and Crowdsale pages

Fixed

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Issue that isn't related RP's feature but anyway.
Publish page: additional tier is rendered after each page refreshing
screen shot 2018-08-22 at 5 46 16 am

**Comment by dennis00010011b** [comment]
@mariano-aguero 
 In the case when user switches between network on Step4/Publish page the warning should look like  warning from contribution page in the same situation

Now 
screen shot 2018-08-22 at 5 54 17 am

Should be 
screen shot 2018-08-22 at 5 59 53 am

**Comment by dennis00010011b** [comment]
@mariano-aguero 
Step 4: transaction is generated after each page refreshing
Steps:
 1. Create a crowdsale and fill out the forms until you reach step 4. Use any network.
 2. Refresh the page 
 3. Observe count of transaction in Nifty wallet
screen shot 2018-08-22 at 6 11 22 am

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Issue that isn't related RP's feature but anyway.

An additional tier no longer appears

https://www.useloom.com/share/56c9e4fbb6ea4f748fafb2b9405e8ca2

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> In the case when user switches between network on Step4/Publish page the warning should look like warning from contribution page in the same situation

Change alert

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> Step 4: transaction is generated after each page refreshing

Speaking with @fernandomg , we thought that the user should cancel the previous transaction (reject). The solution to this problem would imply a very high programming cost which I do not think is the time to face. I think we could create an issue for it and work it after the design application, Do you agree?

**Comment by dennis00010011b** [comment]
@mariano-aguero 
https://github.com/poanetwork/token-wizard/pull/1097#issuecomment-414665526

User able to finish deployment  without signing all transactions
Steps:
 1. Set up account to Sokol network.
 2. Start create the Minted crowdsale, in Step 4 sign 2-3 transaction
 3.  Switch to Kovan network. 
 4. Confirm warning and proceed with  button Continue until Crowdsale page is open.
 5. Switch back to Sokol network.

Actual result: 
 - created crowdsale doesn't match given  in Step3 parameters (because not all contracts were deployed)

Possible solution: 
 1) in Step 4 disable button `continue` if not all transaction signed 
 2) display warning without confirmation button, until user switches back to pristine network

screen shot 2018-08-27 at 12 32 16 pm

**Comment by mariano-aguero** [comment]
@dennis00010011b 

> User able to finish deployment without signing all transactions

I apply the solution _**in Step 4 disable button continue if not all transaction signed**_

Can you check it ? Thanks

**Pull request merged**
