### PR TITLE
(Tests) Add tests for Stores 

### LINKED ISSUE #818: (Tests) Add tests for Stores
Refer to https://github.com/poanetwork/token-wizard/issues/499#issuecomment-383696851

### PR DESCRIPTION
**Pull request by mariano-aguero**
Closes #818 

The store `DeploymentStore.js` will not be covered, because  it was refactored in the PR #1164

Attached coverage image
screenshot_20181010_112916

To run tests execute the following command:
`$ npm run test:dapp -- --coverage`

### CODE REVIEW

**Comment by fernandomg** [comment]
@mariano-aguero 
Tests are not passing in Travis, it's failing with:

> `npm ERR! Invalid: lock file's gulp-sass@2.3.2 does not satisfy gulp-sass@^4.0.1`

**Comment by fernandomg** [comment]
@mariano-aguero on a clean installation, I'm getting this error:

image

**Comment by mariano-aguero** [comment]
@fernandomg 

>  on a clean installation, I'm getting this error:

I update the package script, now it should be initialized correctly
If it continues happening, I would need the steps to be able to reproduce the problem

Regards

**Comment by mariano-aguero** [comment]
@fernandomg 

> Tests are not passing in Travis, it's failing with

I update the package lock file, I only see errors from the e2e tests that already existed

Greetings

**Pull request merged**
